# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build angular project
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        working-directory: ./source/smartdisplay/
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: ./source/smartdisplay/package-lock.json
    - run: npm ci
      working-directory: ./source/smartdisplay/
    - run: npm run build --if-present
      working-directory: ./source/smartdisplay/
